title: "NHC #3 · Apocalypse"
description: "Règlement officiel de la Nuclear Haunted Cup #3 : Apocalypse"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://yekelle.github.io"
baseurl: "/nhc3-reglement"

search_enabled: true
heading_anchors: true

color_scheme: apocalypse
